### PR TITLE
Added AWS2-S3 source kamelet

### LINKED ISSUE #10: Add AWS2-S3 source kamelet

### PR DESCRIPTION
**Pull request by oscerd**
Fixes #10

### CODE REVIEW

**Comment by oscerd** [comment]
cc @nicolaferraro

**Comment by nicolaferraro** [comment]
I think we can stick to one version of the Kamelet here, so I'd remove the `aws-s3-source`. It was copied from an existing example, but there seems there's no reasons to maintain both here, unless they add something from a connector end-user perspective. Wdyt @oscerd ? The Kamelet seems ok.

**Comment by oscerd** [comment]
Sure I can do that in a subsequent pr

**Comment by oscerd** [comment]
@nicolaferraro updated

**Review by nicolaferraro — APPROVED** [review]

**Pull request merged**
