### PR TITLE
Upgrade Camel from 4.0.0-RC1 to 4.0.0

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by claudio4j** [comment]
Camel 4 was just released, can you update to 4.0 ?

**Comment by apupier** [comment]
see https://github.com/apache/camel-kamelets/issues/1579

**Comment by christophd** [comment]
YAKS tests have been fixed with PR #1586
The changes got merged already so cloud you please rebase base on it, thx

**Comment by apupier** [comment]
rebased, require a committer to approve launchign the GitHub workflows

**Pull request merged**
