### PR TITLE
Add Google Big Query Sink Kamelet

### PR DESCRIPTION
**Pull request by claudio4j**
https://github.com/apache/camel-kamelets/issues/843

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by oscerd — CHANGES_REQUESTED** [review]
Looking a bit better at this one, the payload in the body should be a map or a list. So I'm not sure this will work out of the box, since sources are not mapping lists or maps directly.

**Comment by claudio4j** [comment]
The kamelet can expect a json as body and I can add a step to transform the json to map or list of map

**Comment by oscerd** [comment]
This needs to be documented in the description, because otherwise a user might not know what he has to do.

**Review by oscerd — APPROVED** [review]

**Review by oscerd — CHANGES_REQUESTED** [review]
Please add 

```
  types:
    in:
      mediaType: application/json
```

**Review by oscerd — APPROVED** [review]

**Pull request merged**
