### PR TITLE
WIP: Oracle Database Sink & Source

### PR DESCRIPTION
**Pull request by indiealexh**
Add Oracle Database sink and source Kamelet

### CODE REVIEW

**Comment by oscerd** [comment]
We cannot use the drive from ora le due to license. So I would remove the explicit dependency and add the instruction in the description.

**Comment by indiealexh** [comment]
> We cannot use the drive from ora le due to license. So I would remove the explicit dependency and add the instruction in the description.

Can you point to an example of where this has been done before? Perhaps I should just make a generic JDBC Kamelet?

**Comment by oscerd** [comment]
Hello, 

You can do something like this: https://github.com/apache/camel-kamelets/blob/main/kamelets/sqlserver-source.kamelet.yaml#L35

Personally I think makes a generic jdbc kamelet it's a bit too generic. The aim of Kamelets is being able to grab one of them to integrate with a specific external service or db. So IMO, it would be really better to have one Kamelet for each Database kind.

**Comment by oscerd** [comment]
Btw the skeleton of the Kamelet is good, you just need to remove the dependency and add the instruction to the description. Thanks a lot for working on this.

**Comment by oscerd** [comment]
Did you have time to have a look at updating this? Thanks

**Comment by oscerd** [comment]
If you don't mind, I'll clean up and merge this PR.

**Comment by indiealexh** [comment]
> If you don't mind, I'll clean up and merge this PR.

Yeah, sorry been crazy busy at work and havn't had a chance to follow up with this.

**Pull request closed without merging**
