### PR TITLE
KafkaKameletsWithScram512

### PR DESCRIPTION
**Pull request by mthirion**
Added a Kafka sink and Kafka source Kamelet definition that support SCRAM-SHA-512 authentication.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
I would probably change the support.level to Preview, but they are fine. Thanks for this.

**Comment by oscerd** [comment]
I'll fix this later.

**Comment by oscerd** [comment]
Thanks a lot for this PR.

**Comment by Neustradamus** [comment]
@mthirion: Good job!

Linked to:
- https://github.com/scram-sasl/info/issues/1

**Pull request merged**
