### PR TITLE
Add FHIR sink kamelet

### PR DESCRIPTION
**Pull request by bramplouvier**
Please consider adding a FHIR sink Kamelet to the catalog.

### CODE REVIEW

**Comment by bramplouvier** [comment]
I'm testing against a docker instance of the Microsoft FHIR server: https://github.com/microsoft/fhir-server using the camel command line and an integration yaml-file [test-integration-xml.yaml.txt](https://github.com/apache/camel-kamelets/files/10246992/test-integration-xml.yaml.txt).

**Comment by oscerd** [comment]
Thanks for the information

**Comment by oscerd** [comment]
I'll take care of fixing the needed bits.

**Comment by oscerd** [comment]
Thanks a bunch. Contributions are always welcome!

**Pull request merged**
