### PR TITLE
fix #924 Kamelets have wrong type for properties.

### LINKED ISSUE #924: aws-* kamelets heve wrton type for aws_delay property
the `aws_delay` property type is set to `long` that is not a valid json schema type. I think must be changed to either `integer` or `number` (probably the former).

### PR DESCRIPTION
**Pull request by valdar**
added validation of propery types to match json schema allowed values.

### CODE REVIEW

**Comment by oscerd** [comment]
Converted to draft

**Review by oscerd — APPROVED** [review]

**Comment by valdar** [comment]
depends on https://github.com/apache/camel-kamelets/pull/928

**Review by lburgazzoli — APPROVED** [review]

**Comment by oscerd** [comment]
Needs to double check the google authentication.

**Comment by oscerd** [comment]
Could this be rebased or start from scratch again?

**Pull request closed without merging**
