### PR TITLE
Added JMS source kamelet for Apache Artermis

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
How the binding looks like:

```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: jms-source-apache-artemis-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: jms-source-apache-artemis
    properties:
      destinationName: person
      brokerURL: "tcp://redacted:port"
  sink:
    uri: "log:info"
```

**Review by oscerd — APPROVED** [review]

**Review by oscerd — CHANGES_REQUESTED** [review]
Maybe change the name to follow the kamelets naming convention. The content is ok.

**Comment by orpiske** [comment]
> Maybe change the name to follow the kamelets naming convention. The content is ok.

Cool, thanks for taking a look at it Andrea! I'll review the failing checks and put it according to the standard :)

**Comment by orpiske** [comment]
This one is still broken. I am fixing it.

**Comment by orpiske** [comment]
> This one is still broken. I am fixing it.

It should be fine now. It had an extra file.

**Comment by orpiske** [comment]
This and subsequent PRs will have conflicts on the nav file. I am watching for the approvals / comments and will be fixing the conflicts as they appear.

**Review by nicolaferraro — APPROVED** [review]

**Comment by orpiske** [comment]
> Maybe change the name to follow the kamelets naming convention. The content is ok.

Hey @oscerd, do we still have anything to change on this one? I think it's pretty much the same as the others ... I'm wondering if I missed anything.

**Review by oscerd — APPROVED** [review]
Lgtm

**Comment by orpiske** [comment]
> Lgtm

Thanks!

**Pull request merged**
