### PR TITLE
Upgrade Camel K CRDs to 2.0.1

### PR DESCRIPTION
**Pull request by apupier**
Use Kamelet v1 instead of v1alpha1
Keeping KameletBinding and not migrating to Pipes as it is used only in tests and not yet supported in a released version Camel Jbang

part of #1562

### CODE REVIEW

**Comment by apupier** [comment]
current failure:
https://github.com/apupier/camel-kamelets/actions/runs/6082723370/job/16501217219?pr=5#step:7:171
```
Error:  [ERROR] Unknown catalog 'citrusframework/yaks'
```

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
All seems good. @christophd do you mind have a look too?

**Review by christophd — APPROVED** [review]
yes, looking good

**Comment by apupier** [comment]
(reminder that I'm not a committer and cannot merge the Pull Request to be sure that nobody i awaiting for me to merge it)

**Pull request merged**
