### PR TITLE
Add mail sink Kamelet

### PR DESCRIPTION
**Pull request by christophd**

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
The sink yaml in kamelets seems to be different from the one copied in the library. Also i would probably use the same convention of having both ce headers and not supported

**Comment by oscerd** [comment]
Looks good overall

**Comment by christophd** [comment]
@oscerd thanks fixed the kamelet sources. could you please approve the workflow run once more?

**Comment by oscerd** [comment]
Done. Thanks.

**Comment by christophd** [comment]
@oscerd previous workflow run was hanging due to issue with YAKS versioning. Could you please approve once more 🙏 

this hanging workflow can be cancelled https://github.com/apache/camel-kamelets/runs/4433396398?check_suite_focus=true

**Review by oscerd — APPROVED** [review]

**Comment by christophd** [comment]
@oscerd forgot username and password as mandatory Kamelet properties. sorry for the trial end error. I think we are close to getting this test running green 🤞

**Comment by oscerd** [comment]
No worries! Thanks a lot for your time!

**Comment by christophd** [comment]
@oscerd please one more round of approval 🙏

**Comment by christophd** [comment]
@oscerd ha, found a last issue. the test requires both timer-source and mail-sink Kamelet to be available in the namespace. Please approve once more.

**Comment by christophd** [comment]
Wohooo! SUCCESS! @oscerd many thanks for staying with me

**Comment by oscerd** [comment]
Happy to help

**Pull request merged**
