### PR TITLE
Replace to use org.messaginghub:pooled-jms in JMS Pooled Kamelet

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by zhfeng** [comment]
Well `io.quarkiverse.messaginghub:quarkus-pooled-jms` is a extension for quarkus but here in this kamelet I think only  `org.messaginghub:pooled-jms` is needed for `pooledFactoryBean`.

**Comment by oscerd** [comment]
I don't remember the reason but please test the update through camel-jbamg

**Comment by zhfeng** [comment]
Hmm, can you provide the command I need to test by `camel-jbang`?

**Comment by oscerd** [comment]
I meant to say if you can test the kamelet with camel-jbang or what you're using

**Comment by zhfeng** [comment]
Yeah, I run a jbang example from https://github.com/apache/camel-kamelets-examples/tree/main/jbang/timer-activemq-artemis. But how to use the `4.8.0-SNAPSHOT` of `org.apache.camel.kamelets:camel-kamelet` ?

```
jbang -Dcamel.jbang.version=4.8.0-SNAPSHOT camel@apache/camel run artemis-log.camel.yaml --kamelets-version=4.8.0-SNAPSHOT

[jbang] [WARN] Detected missing or out-of-date dependencies in cache.
[jbang] Resolving dependencies...
[jbang]    org.apache.camel:camel-bom:4.8.0-SNAPSHOT@pom
[jbang]    org.apache.camel:camel-jbang-core:4.8.0-SNAPSHOT
[jbang]    org.apache.camel.kamelets:camel-kamelets:4.7.0
[jbang] Dependencies resolved
...
```

@davsclaus @oscerd it's still `4.7.0` even I add ` --kamelets-version=4.8.0-SNAPSHOT`. any hint?

**Comment by davsclaus** [comment]
kamelets JAR is loaded by jbang, so you cannot use --kamelets-version.
Use -Dcamel-kamelets.version=xxx or better just edit the .java file in your ~/.jbang cache folder

**Comment by zhfeng** [comment]
Thanks a lot @davsclaus - Now I can run the example perfectly with the `jbang -Dcamel-kamelets.version=4.8.0-SNAPSHOT`

**Comment by oscerd** [comment]
You can also use --local-kamelet-dir param

**Comment by zhfeng** [comment]
Thanks @oscerd - yeah, it works with `--local-kamelet-dir` as well.

**Comment by zhfeng** [comment]
Just curious, is it possible to use different artifacts based on `runtime` in kamelet?

I'm asking because if we run this kamelt in a `quarkus` runtime, by adding `quarkus-pooled-jms` and `quarkua-artemis`, there is also no need to create a `pooledFactoryBean`.

**Comment by oscerd** [comment]
No, it's not possible, but you can create your own Kamelet and use that directly. The aim of Kamelets is creating a building block to make possible for end-users to create their own catalog.

**Comment by zhfeng** [comment]
Hmm, get it. Is there any label can be used to mark it only used in a specific runtime?

**Pull request merged**
