### PR TITLE
[Docs] Generate kamelets pages using Antora (main)

### PR DESCRIPTION
**Pull request by djencks**
See https://github.com/apache/camel-website/issues/720

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
This needs to take into account also the generator.go script. cc @nicolaferraro

**Comment by djencks** [comment]
Yes, at the moment both  original and new versions of the kamelets pages are shown for easier comparison.
One difference is that I changed how the "required" status of a property is shown to match the other tables I've worked on: instead of a star after the name, the description starts with at bold "Required".

**Comment by nicolaferraro** [comment]
> Yes, at the moment both original and new versions of the kamelets pages are shown for easier comparison. One difference is that I changed how the "required" status of a property is shown to match the other tables I've worked on: instead of a star after the name, the description starts with at bold "Required".

Yes, the generator puts images into assets/images/kamelets, so I think this line needs to be changed: https://github.com/apache/camel-kamelets/blob/381fb8b16e6981203e6bcc329a47793f9b86906e/script/generator/generator.go#L360

**Comment by djencks** [comment]
I’ll try to finish this up…. the new stuff has Antora extract the image from the yml, IIRC the generator is not needed at all.

**Comment by djencks** [comment]
This is ready to review.... would be nice to get it in before there are a lot more new kamelets :-)

**Comment by djencks** [comment]
The generator script only generates the nav file now, but it's still loading the entire yaml into a model because I can't figure out how the name gets into the model or how to get it on it's own.

**Review by oscerd — COMMENTED** [review]
I hope this won't break the projects using this stuff. I'll give a try to the PR locally and check.

**Comment by oscerd** [comment]
LGTM at first sight btw

**Comment by djencks** [comment]
There was a problem with finding the images... not sure how my local builds worked... should be fixed now.

**Comment by djencks** [comment]
I think this PR will be OK but there's a bug in @djencks/asciidoctor-antora-indexer that prevents more than one set of components being generated properly in a full build.  I'll let you know when it's fixed...

**Comment by oscerd** [comment]
Ok, let's wait.

**Comment by djencks** [comment]
This is all fixed (all 3 branches) and the preview is at https://pr-735--camel.netlify.app/

**Comment by oscerd** [comment]
Here 

https://pr-735--camel.netlify.app/camel-kamelets/latest/

I'm getting

This file exists solely to defeat the limitations of the link checker, that is unaware of the .htaccess redirect from this page to the latest released version.

If you see this, you are not viewing the site through httpd or there is something wrong with the .htaccess file: in the latter case please let the camel developers know.

**Comment by djencks** [comment]
Netlify doesn’t understand httpd redirects, as hinted by the second line.

Try https://pr-735--camel.netlify.app/camel-kamelets/0.6.x/index.html

**Comment by oscerd** [comment]
LGTM.

**Comment by oscerd** [comment]
Thanks

**Comment by djencks** [comment]
Is 'LGTM' the same as approval?  I don't know what to do with the "changes requested" review since the code reviewed is gone.

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
yeah, I forgot to approve.

**Pull request merged**
