### PR TITLE
ElasticSearch search source kamelet

### PR DESCRIPTION
**Pull request by Delawen**
Ready to review.

### CODE REVIEW

**Comment by Delawen** [comment]
The output is of type `org.elasticsearch.search.SearchHits`. Is that fine or should I try to "normalize" this to something standard like a String with a JSON?

```[1] 2021-04-26 10:56:34,456 INFO  [info] (Camel (camel-1) thread #0 - timer://tick) Exchange[ExchangePattern: InOnly, BodyType: org.elasticsearch.search.SearchHits, Body: org.elasticsearch.search.SearchHits@393ceaa3]```

**Comment by oscerd** [comment]
Json would be better.

**Comment by Delawen** [comment]
I don't think I can do proper yaks testing against an ElasticSearch.

I am testing that queries like the following work fine with my own ElasticSearch:

```kamel bind "elasticsearch-search-source?clusterName=quickstart&hostAddresses=quickstart-es-http:9200&user=elastic&password=3n766wE6tg1K4uL1m8or4CqB&query=%7B%22query%22:%7B%22match%22:%7B%22test%22:%22123%22%7D%20%7D%20%7D&indexName=data&enableSSL=false" log:info; kamel logs elasticsearch-search-source-to-log```

**Review by nicolaferraro — APPROVED** [review]

**Comment by nicolaferraro** [comment]
Cool, thanks

**Pull request merged**
