### PR TITLE
Use OpenJDK 11 when building with JitPack

### PR DESCRIPTION
**Pull request by christophd**
Relates to #792

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
I've had this in front of my eyes for months. I'm really lazy.

**Comment by christophd** [comment]
you lazy? no way!

I did not care about failing YAKS tests for long time. At least I am glad that the tests seem to point to the problem rigidly. Let's see if this has fixed the issues

**Comment by oscerd** [comment]
Not sure but I guess you'll need to merge anyway and then open a test PR to check.

**Comment by christophd** [comment]
I think it is working as JitPack now uses JDK 11 on my branch:

https://jitpack.io/com/github/christophd/camel-kamelets/3f2ed91323/build.log

You are right that we need to merge here anyway to get the JitPack build also triggered for this repository

**Comment by christophd** [comment]
@oscerd could you please merge. I do not have permissions to do so

**Comment by oscerd** [comment]
Thanks a bunch!

**Pull request merged**
