### PR TITLE
chore: fix generated YAML and required props

### PR DESCRIPTION
**Pull request by nicolaferraro**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
btw is the source code generated list of options in the same order as in the yaml file (eg so users may put the most important in the top).

**Comment by nicolaferraro** [comment]
> btw is the source code generated list of options in the same order as in the yaml file (eg so users may put the most important in the top).

Well, currently it should be alphabetical with required fields first... But we can think about it..

**Comment by nicolaferraro** [comment]
> > btw is the source code generated list of options in the same order as in the yaml file (eg so users may put the most important in the top).
> 
> Well, currently it should be alphabetical with required fields first... But we can think about it..

The problem is that it's a map that loses the order when unmarhsalled..

**Comment by davsclaus** [comment]
> > > btw is the source code generated list of options in the same order as in the yaml file (eg so users may put the most important in the top).
> > 
> > 
> > Well, currently it should be alphabetical with required fields first... But we can think about it..
> 
> The problem is that it's a map that loses the order when unmarhsalled.. that's more a problem that happens e.g. on Kube, once you apply it you lose the order

ah okay A..Z is also fine, just that its the same. 

We had that problem earlier in core camel where a regen would shuffle the options. So its best to have a fixed sorting in the build process

**Pull request merged**
