### PR TITLE
Externalize the Kamelet binding template in the Kafka Source

### PR DESCRIPTION
**Pull request by orpiske**
Move most of the code that generates documentation for bindings into external templates. 

I plan to re-use them to support a new feature for Camel JBang that creates the file for the user.

### CODE REVIEW

**Comment by orpiske** [comment]
I refreshed the documentation as part of this only to showcase that the PR did not result in significant changes to the generated documentation.

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Is the generation script and validation script still ok?

**Comment by orpiske** [comment]
> Is the generation script and validation script still ok?

Yes. Both work just like before.

**Comment by oscerd** [comment]
+1 to merge.

**Pull request merged**
