### PR TITLE
ISSUE WITH KAMELET azure-servicebus-source output is message length i…

### PR DESCRIPTION
**Pull request by oscerd**
…nstead of message

### CODE REVIEW

**Comment by oscerd** [comment]
Fixes #980

**Comment by oscerd** [comment]
@bjethwan

With this you'll get the bytes related to the binaryData.

**Comment by oscerd** [comment]
So you can serialize as json or you can convert the payload to a String.

**Comment by bjethwan** [comment]
@oscerd Thank you !
I was using the same in my local test environment to make the azure kamelet work.

Thank you so much.

**Pull request merged**
